
#-----------------------------------------------------------------------

APP       := WmsPlatform
TARGET    := HttpServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += -I/home/Tars/cpp/thirdparty
LIB       += 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
