// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

#ifndef __WXOAUTH_H_
#define __WXOAUTH_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
using namespace std;
#include "WxUserinfo.h"
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace WmsPlatform
{
    struct WxoauthReq : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "WmsPlatform.WxoauthReq";
        }
        static string MD5()
        {
            return "55420b345e13da84aad635417b0d3f4b";
        }
        WxoauthReq()
        :openId(""),accessToken(""),refreshToken(""),wechatAppId("")
        {
        }
        void resetDefautlt()
        {
            openId = "";
            accessToken = "";
            refreshToken = "";
            wechatAppId = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(openId, 0);
            _os.write(accessToken, 1);
            if (refreshToken != "")
            {
                _os.write(refreshToken, 2);
            }
            if (wechatAppId != "")
            {
                _os.write(wechatAppId, 3);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(openId, 0, true);
            _is.read(accessToken, 1, true);
            _is.read(refreshToken, 2, false);
            _is.read(wechatAppId, 3, false);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(openId,"openId");
            _ds.display(accessToken,"accessToken");
            _ds.display(refreshToken,"refreshToken");
            _ds.display(wechatAppId,"wechatAppId");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(openId, true);
            _ds.displaySimple(accessToken, true);
            _ds.displaySimple(refreshToken, true);
            _ds.displaySimple(wechatAppId, false);
            return _os;
        }
    public:
        std::string openId;
        std::string accessToken;
        std::string refreshToken;
        std::string wechatAppId;
    };
    inline bool operator==(const WxoauthReq&l, const WxoauthReq&r)
    {
        return l.openId == r.openId && l.accessToken == r.accessToken && l.refreshToken == r.refreshToken && l.wechatAppId == r.wechatAppId;
    }
    inline bool operator!=(const WxoauthReq&l, const WxoauthReq&r)
    {
        return !(l == r);
    }


    /* callback of async proxy for client */
    class WxoauthPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~WxoauthPrxCallback(){}
        virtual void callback_test(tars::Int32 ret)
        { throw std::runtime_error("callback_test() override incorrect."); }
        virtual void callback_test_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_test_exception() override incorrect."); }

        virtual void callback_wxchatLogin(tars::Int32 ret,  const WmsPlatform::WxUserinfoRes& res)
        { throw std::runtime_error("callback_wxchatLogin() override incorrect."); }
        virtual void callback_wxchatLogin_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_wxchatLogin_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Wxoauth_all[]=
            {
                "test",
                "wxchatLogin"
            };
            pair<string*, string*> r = equal_range(__Wxoauth_all, __Wxoauth_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Wxoauth_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_test(_ret);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_wxchatLogin_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    WmsPlatform::WxUserinfoRes res;
                    _is.read(res, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_wxchatLogin(_ret, res);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<WxoauthPrxCallback> WxoauthPrxCallbackPtr;

    /* callback of promise async proxy for client */
    class WxoauthPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~WxoauthPrxCallbackPromise(){}
    public:
        struct Promisetest: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< WxoauthPrxCallbackPromise::Promisetest > PromisetestPtr;

        WxoauthPrxCallbackPromise(const promise::Promise< WxoauthPrxCallbackPromise::PromisetestPtr > &promise)
        : _promise_test(promise)
        {}
        
        virtual void callback_test(const WxoauthPrxCallbackPromise::PromisetestPtr &ptr)
        {
            _promise_test.setValue(ptr);
        }
        virtual void callback_test_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:test_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_test.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< WxoauthPrxCallbackPromise::PromisetestPtr > _promise_test;

    public:
        struct PromisewxchatLogin: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            WmsPlatform::WxUserinfoRes res;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< WxoauthPrxCallbackPromise::PromisewxchatLogin > PromisewxchatLoginPtr;

        WxoauthPrxCallbackPromise(const promise::Promise< WxoauthPrxCallbackPromise::PromisewxchatLoginPtr > &promise)
        : _promise_wxchatLogin(promise)
        {}
        
        virtual void callback_wxchatLogin(const WxoauthPrxCallbackPromise::PromisewxchatLoginPtr &ptr)
        {
            _promise_wxchatLogin.setValue(ptr);
        }
        virtual void callback_wxchatLogin_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:wxchatLogin_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_wxchatLogin.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< WxoauthPrxCallbackPromise::PromisewxchatLoginPtr > _promise_wxchatLogin;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Wxoauth_all[]=
            {
                "test",
                "wxchatLogin"
            };

            pair<string*, string*> r = equal_range(__Wxoauth_all, __Wxoauth_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Wxoauth_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    WxoauthPrxCallbackPromise::PromisetestPtr ptr = new WxoauthPrxCallbackPromise::Promisetest();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_test(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_wxchatLogin_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    WxoauthPrxCallbackPromise::PromisewxchatLoginPtr ptr = new WxoauthPrxCallbackPromise::PromisewxchatLogin();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->res, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_wxchatLogin_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_wxchatLogin_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_wxchatLogin(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<WxoauthPrxCallbackPromise> WxoauthPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class WxoauthCoroPrxCallback: public WxoauthPrxCallback
    {
    public:
        virtual ~WxoauthCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Wxoauth_all[]=
            {
                "test",
                "wxchatLogin"
            };

            pair<string*, string*> r = equal_range(__Wxoauth_all, __Wxoauth_all+2, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Wxoauth_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_test_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(msg->response.context);

                        callback_test(_ret);

                    }
                    catch(std::exception &ex)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_test_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_wxchatLogin_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        WmsPlatform::WxUserinfoRes res;
                        _is.read(res, 2, true);
                        setResponseContext(msg->response.context);

                        callback_wxchatLogin(_ret, res);

                    }
                    catch(std::exception &ex)
                    {
                        callback_wxchatLogin_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_wxchatLogin_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<WxoauthCoroPrxCallback> WxoauthCoroPrxCallbackPtr;

    /* proxy for client */
    class WxoauthProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 test(const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"test", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_test(WxoauthPrxCallbackPtr callback,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"test", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< WxoauthPrxCallbackPromise::PromisetestPtr > promise_async_test(const map<string, string>& context)
        {
            promise::Promise< WxoauthPrxCallbackPromise::PromisetestPtr > promise;
            WxoauthPrxCallbackPromisePtr callback = new WxoauthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"test", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_test(WxoauthCoroPrxCallbackPtr callback,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"test", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 wxchatLogin(const WmsPlatform::WxoauthReq & req,WmsPlatform::WxUserinfoRes &res,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(req, 1);
            _os.write(res, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"wxchatLogin", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(res, 2, true);
            return _ret;
        }

        void async_wxchatLogin(WxoauthPrxCallbackPtr callback,const WmsPlatform::WxoauthReq &req,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"wxchatLogin", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< WxoauthPrxCallbackPromise::PromisewxchatLoginPtr > promise_async_wxchatLogin(const WmsPlatform::WxoauthReq &req,const map<string, string>& context)
        {
            promise::Promise< WxoauthPrxCallbackPromise::PromisewxchatLoginPtr > promise;
            WxoauthPrxCallbackPromisePtr callback = new WxoauthPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"wxchatLogin", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_wxchatLogin(WxoauthCoroPrxCallbackPtr callback,const WmsPlatform::WxoauthReq &req,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(req, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"wxchatLogin", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        WxoauthProxy* tars_hash(int64_t key)
        {
            return (WxoauthProxy*)ServantProxy::tars_hash(key);
        }

        WxoauthProxy* tars_consistent_hash(int64_t key)
        {
            return (WxoauthProxy*)ServantProxy::tars_consistent_hash(key);
        }

        WxoauthProxy* tars_set_timeout(int msecond)
        {
            return (WxoauthProxy*)ServantProxy::tars_set_timeout(msecond);
        }

    };
    typedef tars::TC_AutoPtr<WxoauthProxy> WxoauthPrx;

    /* servant for server */
    class Wxoauth : public tars::Servant
    {
    public:
        virtual ~Wxoauth(){}
        virtual tars::Int32 test(tars::TarsCurrentPtr current) = 0;
        static void async_response_test(tars::TarsCurrentPtr current, tars::Int32 _ret)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 wxchatLogin(const WmsPlatform::WxoauthReq & req,WmsPlatform::WxUserinfoRes &res,tars::TarsCurrentPtr current) = 0;
        static void async_response_wxchatLogin(tars::TarsCurrentPtr current, tars::Int32 _ret, const WmsPlatform::WxUserinfoRes &res)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("res", res);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(res, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __WmsPlatform__Wxoauth_all[]=
            {
                "test",
                "wxchatLogin"
            };

            pair<string*, string*> r = equal_range(__WmsPlatform__Wxoauth_all, __WmsPlatform__Wxoauth_all+2, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __WmsPlatform__Wxoauth_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                    }
                    else
                    {
                    }
                    tars::Int32 _ret = test(_current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    WmsPlatform::WxoauthReq req;
                    WmsPlatform::WxUserinfoRes res;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("req", req);
                        tarsAttr.getByDefault("res", res, res);
                    }
                    else
                    {
                        _is.read(req, 1, true);
                        _is.read(res, 2, false);
                    }
                    tars::Int32 _ret = wxchatLogin(req,res, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("res", res);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(res, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
